language: python
python:
- 3.5
install:
- pip install -r requirements.txt
- gem install bundle
- python manage.py install_all_govuk_assets
script:
- true
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: tom.dolan@digital.cabinet-office.gov.uk
  password:
    secure: gq4I6D16o52mUOyI/xl1kqaIN8RBuwNkMh7C6U4zE8b0xgBSIsqo7m+T+uwLweOnzEFOqMju0v2e1qJXRO+Daluk3h92sJC09Wiznt2ReTohcfJ3PpXuiLKAlQ08F7pIhp2Gz/vIU/FZSfeREl3jiw8Ndne+rqEEl+nuh2tKPVcrybKILHVWp29D0KiMnsjrlpLR9pgYEMnTmlrjghZMkBqhRvui5zz/FGvUbe2/+gU2b/hdp936pIdL3r8YJTNB1ZtO+S1usmfyu6rbfp+r1mNw5XPS37DyTm1AuhD+TN6Bb+xWJb85hxqYlQxHGbPLDYW084I4qtXQLrkJeYQ5xGm2r/CU24We8sRIoHAyu6JTc9U9US6g6tgvferT+fef06DofY1N+FNFCwoEH2NuMsBcSLlPGjx6+gTmepLc6Kj07elbcSI70OW9d35hH3Zddsk7MhWvdC+rCtLBVItNejFBoOzTdWX86YjjxaIavE9wrizI7DIlTT38qSOP2n6Aj3/xi7Vy+E2CVVyJq3MiAir7mi/yjnT77gQdQGhUNHROrDBRjtA2ZuUye6u2rMm4s04L+UoJO7TMW7Fz6yrAg4uhzhajcWfDqbnsvJu7fr8cQJmuP0vWsxUZN4qnuR54IMeLG+dyanIwaChGBVgZ/CBobEQxZ5Tyqv4bsHcOTf8=
  organization: paas-demo
  space: sandbox
  on:
    repo: tomskerous/paas-ss-proto
notifications:
  email: false
sudo: false
env:
  global:
  - secure: esj3ut+TwKX25QzU1koJyTVIX+x1V55graI65X8LiYXKcOP040VPJ9lIC0HeRs5UViBM0Ur1F93rGdgW2zYVzu5MLZoH7KjpzMcG30x+FDqLChT0JfNcLLtLm/wIhx/OAAmsBxXlvjPp092BeEKd3Jug8d329TxwwK5G5XxAatg=
